# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: pangeo
channels:
  - conda-forge
dependencies:
  - jupyterlab=1
  - dask=2
  - dask-kubernetes=0.9
  - dask-labextension=1
  - graphviz
