name: pangeo
channels:
  - conda-forge
dependencies:
  - nomkl
  - s3fs
  - gcsfs
  - intake
  - intake-xarray
  - msgpack-python
  - curl
  - python
  - xarray
  - zarr 
  - h5py
  - h5netcdf
  - dask
  - distributed
  - dask-kubernetes
  - matplotlib
  - nbserverproxy
  - jupyter
  - ipywidgets
  - graphviz
  - jupyterlab
  - libgdal
  - boto3
  - hvplot
  - geoviews-core
  - ipyleaflet
  - datashader
  - requests
  - pandas
  - geopandas
  - rasterio
  - tornado
  - pip:
    - sat-search
    - dask-labextension
