name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab>=1.0.0
  - jupyterhub
  - tornado=5.1.1
  - notebook=5.7.4
  - bokeh
  - dask>=2.0.0
  - dask-kubernetes>=0.9.0
  - jupyter-server-proxy
  - ipywidgets
  - graphviz
  - dask-labextension>=1.0.0
